UART Class Reference
#include <uart.h>
Public Member Functions
UART ()
void WyslijString (const char *txt)
Private Member Functions
void WyslijZnak (char znak)
Detailed Description
Definition at line 11 of file uart.h.
Constructor & Destructor Documentation
UART::UART ()
Definition at line 10 of file uart.cpp.
Member Function Documentation
void UART::WyslijString (const char * txt)
Definition at line 22 of file uart.cpp.
References WyslijZnak().
Referenced by main().
void UART::WyslijZnak (char znak) [private]
Definition at line 16 of file uart.cpp.
Referenced by WyslijString().
The documentation for this class was generated from the following files:
uart.h
uart.cpp